/*
 * This file was automatically generated by EvoSuite
 * Mon May 24 13:06:55 GMT 2021
 */

package de.gurkenlabs.litiengine.util.geom;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import de.gurkenlabs.litiengine.util.geom.GeometricUtilities;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;
import java.awt.geom.GeneralPath;
import java.awt.geom.Line2D;
import java.awt.geom.Path2D;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RectangularShape;
import java.awt.geom.RoundRectangle2D;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GeometricUtilities_ESTest extends GeometricUtilities_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      RoundRectangle2D.Float roundRectangle2D_Float0 = new RoundRectangle2D.Float(127.67403F, (-717.433F), 1098.7069F, 127.67403F, (-717.433F), (-717.433F));
      Rectangle2D rectangle2D0 = roundRectangle2D_Float0.getBounds2D();
      Point point0 = new Point(874, (-2385));
      GeometricUtilities.translateShape(rectangle2D0, point0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      Point point0 = new Point((-1215), (-371));
      Rectangle rectangle0 = new Rectangle(point0);
      Rectangle2D rectangle2D0 = rectangle2D_Float0.createIntersection(rectangle0);
      GeometricUtilities.scaleRect(rectangle2D0, 0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Point2D.Float point2D_Float0 = new Point2D.Float(713.0F, 713.0F);
      Point point0 = new Point(1783004650, (-2964));
      GeometricUtilities.project((Point2D) point0, (Point2D) point2D_Float0, 1.0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Point2D.Float point2D_Float0 = new Point2D.Float(0.0F, 0.0F);
      Point2D point2D0 = GeometricUtilities.project((Point2D) point2D_Float0, (Point2D) point2D_Float0, (-1.0));
      Ellipse2D ellipse2D0 = GeometricUtilities.getCircle(point2D0, 0.0);
      GeometricUtilities.intersects(ellipse2D0, ellipse2D0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Point point0 = new Point();
      Ellipse2D ellipse2D0 = GeometricUtilities.getCircle(point0, 1.0);
      Ellipse2D.Float ellipse2D_Float0 = new Ellipse2D.Float((-128.72081F), 0.0F, 0, 1059.7964F);
      GeometricUtilities.intersects(ellipse2D0, (Ellipse2D) ellipse2D_Float0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Ellipse2D.Double ellipse2D_Double0 = new Ellipse2D.Double(0.0, 226.434445319, (-2820.5024663221907), 21.177359357114938);
      GeometricUtilities.intersects((Ellipse2D) ellipse2D_Double0, (Ellipse2D) ellipse2D_Double0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double(21.483200000000124, 21.483200000000124, 21.483200000000124, 21.483200000000124);
      rectangle2D_Double0.setFrameFromDiagonal(1809.3549235435942, 12.483200000000124, (-3111.1366541047), 12.483200000000124);
      Point point0 = new Point();
      Dimension dimension0 = new Dimension(0, (-3686));
      Rectangle rectangle0 = new Rectangle(point0, dimension0);
      GeometricUtilities.intersects((Rectangle2D) rectangle0, (Rectangle2D) rectangle2D_Double0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double((-2006.36945663), (-2006.36945663), 0.0, 1.0);
      Rectangle rectangle0 = new Rectangle();
      Rectangle rectangle1 = rectangle2D_Double0.getBounds();
      Rectangle2D rectangle2D0 = rectangle1.createIntersection(rectangle0);
      GeometricUtilities.intersects((Rectangle2D) rectangle1, rectangle2D0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Point2D point2D0 = GeometricUtilities.project((Point2D) point2D_Double0, (double) 0, (-1.0));
      GeometricUtilities.getPointsBetweenPoints(point2D_Double0, point2D0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      List<Point2D> list0 = GeometricUtilities.getPoints((Rectangle2D) rectangle2D_Float0);
      Point2D point2D0 = GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      Line2D.Double line2D_Double0 = new Line2D.Double(point2D0, point2D0);
      Rectangle rectangle0 = line2D_Double0.getBounds();
      rectangle0.translate(978, 978);
      Point2D point2D1 = GeometricUtilities.getCenter((RectangularShape) rectangle0);
      GeometricUtilities.getPointsBetweenPoints(point2D0, point2D1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Point point0 = new Point();
      Point2D point2D0 = GeometricUtilities.project((Point2D) point0, (double) 0, 5302.655778091);
      Point2D point2D1 = GeometricUtilities.getCenter((-2274.0), (-2793.80626127191), (-2005.86945663), 270.0);
      GeometricUtilities.getPointsBetweenPoints(point2D0, point2D1);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter((-2793.80626127191), 0.0, (-2793.80626127191), 357.79994);
      GeometricUtilities.getPointsBetweenPoints(point2D0, point2D0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Point point0 = new Point();
      Point2D point2D0 = GeometricUtilities.project((Point2D) point0, (-2006.36945663), 1.0);
      GeometricUtilities.getPointOnCircle(point2D0, (-2006.36945663), 16384.0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      List<Point2D> list0 = GeometricUtilities.getPoints((Rectangle2D) rectangle2D_Float0);
      Point2D point2D0 = GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      Line2D.Double line2D_Double0 = new Line2D.Double(2.846997202896E12, 1.0, 0.0, 0.0);
      GeometricUtilities.getPerpendicularIntersection(point2D0, line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Line2D.Double line2D_Double0 = new Line2D.Double((-1.0), 90.0, 28, 90.0);
      GeometricUtilities.getPerpendicularIntersection(point2D_Double0, line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      GeometricUtilities.getDeltaY(16384.0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      GeometricUtilities.getDeltaX(0.0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter(16384.0, 16384.0, (-1457.3959955), 16384.0);
      GeometricUtilities.equals(point2D0, point2D0, 0.0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Dimension dimension0 = new Dimension((-248), 327);
      Rectangle rectangle0 = new Rectangle(dimension0);
      Rectangle2D rectangle2D0 = GeometricUtilities.extrude(rectangle0, 0);
      Point2D point2D0 = GeometricUtilities.getCenter((RectangularShape) rectangle2D0);
      GeometricUtilities.distance((Rectangle2D) rectangle0, point2D0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      GeometricUtilities.distance((-3203.28147804), 41.09492889202005, 0.9948638094376712, (-3110.021598669555));
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      GeometricUtilities.scaleWithRatio((-1245.0F), 262.69183F, 0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      GeometricUtilities.scaleWithRatio(547.597308697558, 547.597308697558, (-851));
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      GeometricUtilities.scaleShape((Shape) null, 16384.0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      GeometricUtilities.normalizeAngle(0.0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      GeneralPath generalPath0 = new GeneralPath();
      GeometricUtilities.getPoints((Path2D) generalPath0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Dimension dimension0 = new Dimension((-1), 4095);
      Rectangle rectangle0 = new Rectangle(dimension0);
      GeometricUtilities.getLines(rectangle0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double((-2006.36945663), (-2006.36945663), 0.0, 1.0);
      GeometricUtilities.getDiagonal(rectangle2D_Double0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      GeometricUtilities.getDeltaY(0.0, 0.0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      GeometricUtilities.getDeltaY((-1.0), 262.75541069933854);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      GeometricUtilities.getDeltaX((-2793.80626127191), 381.47139999999996);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      GeometricUtilities.getDeltaX(2.0541147930000002E9, (-2006.36945663));
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      GeometricUtilities.getDeltaX(29.0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Area area0 = new Area();
      GeometricUtilities.getConstrainingLines(area0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Point point0 = new Point();
      GeometricUtilities.getCircle(point0, (-2632.024752467));
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      GeometricUtilities.getCircle(point2D_Double0, 0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter(16384.0, 16384.0, 16384.0, 16384.0);
      Ellipse2D ellipse2D0 = GeometricUtilities.getCircle(point2D0, 16384.0);
      GeometricUtilities.intersects(ellipse2D0, ellipse2D0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter((-2009.1889), 0.0, (-1054.7539657), (-4068.6419914));
      GeometricUtilities.getCircle(point2D0, (-1054.7539657));
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double(4.0, 4.0, 4.0, 1.0);
      GeometricUtilities.extrude(rectangle2D_Double0, 1.0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Dimension dimension0 = new Dimension();
      Rectangle rectangle0 = new Rectangle(dimension0);
      rectangle0.setBounds(0, 0, 938, 0);
      GeometricUtilities.extrude(rectangle0, 786.4075192452923);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double((-2006.36945663), (-2006.36945663), 0.0, 1.0);
      GeometricUtilities.extrude(rectangle2D_Double0, 0.0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Point point0 = new Point();
      GeometricUtilities.distance((Point2D) point0, (Point2D) point0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter(16384.0, 16384.0, (-1457.3959955), 16384.0);
      Point2D point2D1 = GeometricUtilities.getCenter(1166.6, (-309.1681451), 360.0, (double) 0.0F);
      GeometricUtilities.distance(point2D1, point2D0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      GeometricUtilities.distance(100.0, 100.0, 100.0, 100.0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Rectangle rectangle0 = new Rectangle();
      Point2D point2D0 = GeometricUtilities.getCenter((RectangularShape) rectangle0);
      Point point0 = new Point(4, (-1082));
      Point point1 = new Point();
      Point2D point2D1 = GeometricUtilities.getCenter((Point2D) point1, (Point2D) point0);
      GeometricUtilities.calcRotationAngleInDegrees(point2D1, point2D0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.shapeIntersects((Shape) null, (Shape) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      // Undeclared exception!
      try { 
        GeometricUtilities.rayCastPoints((Point2D) null, rectangle2D_Float0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.geom.Point2D", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.project((Point2D) null, 0.5, (-590.771));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Rectangle rectangle0 = new Rectangle(918, 918, (-1), 4096);
      // Undeclared exception!
      try { 
        GeometricUtilities.intersects((Rectangle2D) null, (Rectangle2D) rectangle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.intersects((Ellipse2D) null, (Ellipse2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getPointsBetweenPoints((Point2D) null, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getPoints((Rectangle2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getPoints((Path2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      // Undeclared exception!
      try { 
        GeometricUtilities.getIntersectionPoints(line2D_Double0, (Rectangle2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      GeneralPath generalPath0 = new GeneralPath();
      Rectangle rectangle0 = generalPath0.getBounds();
      // Undeclared exception!
      try { 
        GeometricUtilities.getIntersectionPoint((Line2D) null, (Rectangle2D) rectangle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getIntersectionPoint((Line2D) null, (Line2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getConstrainingLines((Area) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getCenter((RectangularShape) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getCenter((Point2D) null, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getCenter((Line2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getAveragePosition((Collection<Point2D>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.extrude((Rectangle2D) null, 0.0F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.equals((Point2D) null, (Point2D) null, 327.1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.distance((Rectangle2D) null, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Area area0 = new Area();
      Rectangle rectangle0 = area0.getBounds();
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float(0, 0, 0.0F, 5637.0F);
      Rectangle2D rectangle2D0 = rectangle2D_Float0.createUnion(rectangle0);
      // Undeclared exception!
      try { 
        GeometricUtilities.contains(rectangle2D0, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.calcRotationAngleInDegrees((Point2D) null, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      GeneralPath generalPath0 = new GeneralPath();
      GeometricUtilities.shapeIntersects(generalPath0, generalPath0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      GeometricUtilities.scaleWithRatio(5, 5, 5);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      GeometricUtilities.scaleWithRatio(0.0F, 0.0F, 2034);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Point2D.Float point2D_Float0 = new Point2D.Float(0.0F, 0.0F);
      Point2D[] point2DArray0 = new Point2D[3];
      point2DArray0[0] = (Point2D) point2D_Float0;
      point2DArray0[1] = (Point2D) point2D_Float0;
      point2DArray0[2] = (Point2D) point2D_Float0;
      GeometricUtilities.getAveragePosition(point2DArray0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Point2D[] point2DArray0 = new Point2D[0];
      GeometricUtilities.getAveragePosition(point2DArray0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Point2D[] point2DArray0 = new Point2D[3];
      // Undeclared exception!
      try { 
        GeometricUtilities.getAveragePosition(point2DArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Dimension dimension0 = new Dimension(2140867721, 1);
      Point point0 = new Point();
      Rectangle rectangle0 = new Rectangle(point0, dimension0);
      Line2D.Float line2D_Float0 = new Line2D.Float(2140867721, (-356.14862F), 2140867721, 0);
      GeometricUtilities.getIntersectionPoints(line2D_Float0, rectangle0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Dimension dimension0 = new Dimension(380, 380);
      Point point0 = new Point();
      Point point1 = new Point(point0);
      point1.y = 3;
      Rectangle rectangle0 = new Rectangle(point1, dimension0);
      Line2D.Double line2D_Double0 = new Line2D.Double(0, 16384.0, 380, 3);
      GeometricUtilities.getIntersectionPoints(line2D_Double0, rectangle0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double(15.483200000000124, 12.483200000000124);
      Arc2D.Double arc2D_Double0 = new Arc2D.Double();
      Point2D point2D0 = arc2D_Double0.getStartPoint();
      Line2D.Double line2D_Double0 = new Line2D.Double(point2D0, point2D_Double0);
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float(0, 0.0F, 11.377778F, 0.0F);
      GeometricUtilities.getIntersectionPoints(line2D_Double0, rectangle2D_Float0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      RoundRectangle2D.Float roundRectangle2D_Float0 = new RoundRectangle2D.Float(129.801F, (-717.433F), 1098.7069F, 129.801F, (-717.433F), (-717.433F));
      Rectangle2D rectangle2D0 = roundRectangle2D_Float0.getBounds2D();
      Line2D.Float line2D_Float0 = new Line2D.Float(129.801F, (-717.433F), 0.0F, 0.0F);
      GeometricUtilities.getIntersectionPoints(line2D_Float0, rectangle2D0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double(21.483200000000124, 21.483200000000124, 21.483200000000124, 21.483200000000124);
      Line2D.Double line2D_Double0 = new Line2D.Double(141.89786830692216, 4.0, 4.0, 2157.81);
      GeometricUtilities.getIntersectionPoints(line2D_Double0, rectangle2D_Double0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Point point0 = new Point();
      Point2D.Double point2D_Double0 = new Point2D.Double(15.483200000000124, 12.483200000000124);
      Line2D.Double line2D_Double0 = new Line2D.Double(point0, point2D_Double0);
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double();
      Rectangle rectangle0 = new Rectangle(0, 2142415476, 0, 0);
      Rectangle2D rectangle2D0 = GeometricUtilities.extrude(rectangle0, 0.0);
      Rectangle2D rectangle2D1 = rectangle2D_Double0.createIntersection(rectangle2D0);
      GeometricUtilities.getIntersectionPoints(line2D_Double0, rectangle2D1);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Dimension dimension0 = new Dimension(380, 380);
      Point point0 = new Point();
      Rectangle rectangle0 = new Rectangle(point0, dimension0);
      Line2D.Double line2D_Double0 = new Line2D.Double(0.0, 380, 1344.23384, 4.0);
      GeometricUtilities.getIntersectionPoints(line2D_Double0, rectangle0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double((-972787.568359375), 2140867721, 47393.5, (-64.4196));
      Line2D.Float line2D_Float0 = new Line2D.Float(0.0F, 710.3428F, 3063.6548F, 2.14086771E9F);
      GeometricUtilities.getIntersectionPoint((Line2D) line2D_Double0, (Line2D) line2D_Float0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double(141.89786830692216, 4.0, 4.0, 2157.81);
      Line2D.Float line2D_Float0 = new Line2D.Float((-0.6420689F), (-0.6420689F), (-0.6420689F), 0);
      GeometricUtilities.getIntersectionPoint((Line2D) line2D_Float0, (Line2D) line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double(141.89786830692216, 4.0, 4.0, 2157.81);
      Line2D.Float line2D_Float0 = new Line2D.Float(0.0F, 0.0F, (-0.6420689F), 0);
      GeometricUtilities.getIntersectionPoint((Line2D) line2D_Float0, (Line2D) line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double(1029.217302017, (-936.728208011902), 0.5F, -0.0);
      Line2D.Float line2D_Float0 = new Line2D.Float(0.0F, 649.9F, 4096.0F, 0);
      GeometricUtilities.getIntersectionPoint((Line2D) line2D_Double0, (Line2D) line2D_Float0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Line2D.Float line2D_Float0 = new Line2D.Float();
      Line2D.Double line2D_Double0 = new Line2D.Double(point2D_Double0, point2D_Double0);
      GeometricUtilities.getIntersectionPoint((Line2D) line2D_Float0, (Line2D) line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Line2D.Float line2D_Float0 = new Line2D.Float(2140867721, (-356.14862F), 2140867721, 0);
      Line2D.Double line2D_Double0 = new Line2D.Double((-636.16294618993), 1.0, 0, (-65248.951109466296));
      GeometricUtilities.getIntersectionPoint((Line2D) line2D_Float0, (Line2D) line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter((-580.9695615729969), (-580.9695615729969), (-297.24), 10.0);
      Point2D[] point2DArray0 = new Point2D[8];
      point2DArray0[0] = point2D0;
      point2DArray0[1] = point2D0;
      point2DArray0[2] = point2D0;
      point2DArray0[3] = point2D0;
      point2DArray0[4] = point2D0;
      point2DArray0[5] = point2D0;
      point2DArray0[6] = point2D0;
      point2DArray0[7] = point2D0;
      GeometricUtilities.getConnectingLines(point2D0, point2DArray0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Point2D[] point2DArray0 = new Point2D[3];
      // Undeclared exception!
      try { 
        GeometricUtilities.getConnectingLines((Point2D) null, point2DArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Point2D point2D0 = GeometricUtilities.getCenter(16384.0, 16384.0, (-1457.3959955), 16384.0);
      GeometricUtilities.equals(point2D0, point2D0, (-1192.4453477));
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      List<Point2D> list0 = GeometricUtilities.getPoints((Rectangle2D) rectangle2D_Float0);
      Point2D point2D0 = GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      Point point0 = new Point();
      GeometricUtilities.equals((Point2D) point0, point2D0, 5568.405);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double((-2006.36945663), (-2006.36945663), 0.0, 1.0);
      rectangle2D_Double0.setFrameFromDiagonal(2006.36945663, 0.0, (-2006.36945663), (-2006.36945663));
      Point point0 = new Point();
      Point2D point2D0 = GeometricUtilities.project((Point2D) point0, (double) 0, 5302.655778091);
      GeometricUtilities.contains(rectangle2D_Double0, point2D0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Area area0 = new Area();
      Rectangle rectangle0 = area0.getBounds();
      Point2D point2D0 = GeometricUtilities.project((Point2D) point2D_Double0, (-2849.0), 1.0);
      GeometricUtilities.contains(rectangle0, point2D0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Ellipse2D.Double ellipse2D_Double0 = new Ellipse2D.Double();
      Rectangle2D rectangle2D0 = ellipse2D_Double0.getBounds2D();
      Point2D.Double point2D_Double0 = new Point2D.Double();
      point2D_Double0.y = (-186.811);
      GeometricUtilities.contains(rectangle2D0, point2D_Double0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Point point0 = new Point();
      Point2D point2D0 = GeometricUtilities.project((Point2D) point0, (Point2D) point0, (double) 0);
      Area area0 = new Area();
      Rectangle rectangle0 = area0.getBounds();
      GeometricUtilities.contains(rectangle0, point2D0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Ellipse2D.Double ellipse2D_Double0 = new Ellipse2D.Double();
      Rectangle2D rectangle2D0 = ellipse2D_Double0.getBounds2D();
      Point2D.Double point2D_Double0 = new Point2D.Double();
      GeometricUtilities.contains(rectangle2D0, point2D_Double0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      GeometricUtilities.calcRotationAngleInDegrees(0.01, 0.01, 0.01, 0.01);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      GeometricUtilities.calcRotationAngleInDegrees((-2006.36945663), (-2006.36945663), (-2006.36945663), (-910.8726712996752));
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      GeometricUtilities.getDeltaY((double) (-0.6420689F), (-3110.021598669555));
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getLines((Rectangle2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      GeometricUtilities.getDeltaX(0.0, 2784.2025);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      GeometricUtilities.normalizeAngle((-1.0984625395962637));
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      GeometricUtilities.normalizeAngle(16384.0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      List<Point2D> list0 = GeometricUtilities.getPoints((Rectangle2D) rectangle2D_Float0);
      Point2D point2D0 = GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      Ellipse2D ellipse2D0 = GeometricUtilities.getCircle(point2D0, 2784.2025);
      GeometricUtilities.shapeIntersects(ellipse2D0, ellipse2D0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Dimension dimension0 = new Dimension(2140867721, 1);
      Point point0 = new Point();
      Rectangle rectangle0 = new Rectangle(point0, dimension0);
      Line2D.Double line2D_Double0 = new Line2D.Double(1769.681675832, (-4319.5), 1.0, 2140867721);
      GeometricUtilities.shapeIntersects(rectangle0, line2D_Double0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float(5, 5, 5, 5);
      GeometricUtilities.shapeIntersects(rectangle2D_Float0, rectangle2D_Float0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      GeometricUtilities.scaleWithRatio(5.0F, 1216422.4700927734, 5);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      GeometricUtilities.scaleWithRatio(5, 2.0, 5);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      GeometricUtilities.scaleWithRatio(4057.1546259, 0.0F, (-2145106798));
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      GeometricUtilities.scaleRect(rectangle2D_Float0, 22);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double(5, 5, 5, 5);
      Point2D.Float point2D_Float0 = new Point2D.Float();
      point2D_Float0.x = (float) 5;
      GeometricUtilities.rayCastPoints(point2D_Float0, rectangle2D_Double0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Ellipse2D.Float ellipse2D_Float0 = new Ellipse2D.Float(0.0F, 321.589F, 16384.0F, 321.589F);
      Ellipse2D.Float ellipse2D_Float1 = new Ellipse2D.Float();
      GeometricUtilities.intersects((Ellipse2D) ellipse2D_Float1, (Ellipse2D) ellipse2D_Float0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Ellipse2D.Float ellipse2D_Float0 = new Ellipse2D.Float();
      GeometricUtilities.intersects((Ellipse2D) ellipse2D_Float0, (Ellipse2D) ellipse2D_Float0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Ellipse2D.Double ellipse2D_Double0 = new Ellipse2D.Double(2281.693491252483, 2281.693491252483, 2281.693491252483, (-161.99846230434161));
      GeometricUtilities.intersects((Ellipse2D) ellipse2D_Double0, (Ellipse2D) ellipse2D_Double0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Dimension dimension0 = new Dimension(380, 380);
      Point point0 = new Point();
      Rectangle rectangle0 = new Rectangle(point0, dimension0);
      Rectangle rectangle1 = new Rectangle(380, 0, 380, 0);
      rectangle1.setLocation(point0);
      GeometricUtilities.intersects((Rectangle2D) rectangle0, (Rectangle2D) rectangle1);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Dimension dimension0 = new Dimension(380, 380);
      Point point0 = new Point();
      Rectangle rectangle0 = new Rectangle(point0, dimension0);
      GeometricUtilities.intersects((Rectangle2D) rectangle0, (Rectangle2D) rectangle0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      GeneralPath generalPath0 = new GeneralPath();
      Rectangle2D rectangle2D0 = generalPath0.getBounds2D();
      GeometricUtilities.intersects(rectangle2D0, rectangle2D0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Point point0 = new Point();
      Line2D.Double line2D_Double0 = new Line2D.Double();
      Point2D point2D0 = GeometricUtilities.getPerpendicularIntersection(point0, line2D_Double0);
      Point2D point2D1 = GeometricUtilities.getCenter((Point2D) point0, point2D0);
      // Undeclared exception!
      GeometricUtilities.getPointsBetweenPoints(point2D1, point0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float(5, 5, 5, 5);
      Path2D.Float path2D_Float0 = new Path2D.Float(rectangle2D_Float0);
      List<Point2D> list0 = GeometricUtilities.getPoints((Path2D) path2D_Float0);
      Point2D.Double point2D_Double0 = (Point2D.Double)GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      assertEquals(5.833333333333333, point2D_Double0.y, 0.01);
      assertNotNull(point2D_Double0);
      assertEquals(5.833333333333333, point2D_Double0.x, 0.01);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      LinkedList<Point2D> linkedList0 = new LinkedList<Point2D>();
      Point2D point2D0 = GeometricUtilities.getAveragePosition((Collection<Point2D>) linkedList0);
      assertNull(point2D0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      double double0 = GeometricUtilities.getDiagonal((Rectangle2D) null);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Line2D.Float line2D_Float0 = new Line2D.Float(11.377778F, 11.377778F, 11.377778F, 3095.0F);
      GeneralPath generalPath0 = new GeneralPath(line2D_Float0);
      Rectangle rectangle0 = generalPath0.getBounds();
      Point2D point2D0 = GeometricUtilities.getIntersectionPoint((Line2D) line2D_Float0, (Rectangle2D) rectangle0);
      assertNull(point2D0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Line2D.Float line2D_Float0 = new Line2D.Float(5, 913.5F, 11.377778F, 5);
      GeneralPath generalPath0 = new GeneralPath(line2D_Float0);
      Rectangle rectangle0 = generalPath0.getBounds();
      Point2D.Double point2D_Double0 = (Point2D.Double)GeometricUtilities.getIntersectionPoint((Line2D) line2D_Float0, (Rectangle2D) rectangle0);
      assertEquals(5.0, point2D_Double0.y, 0.01);
      assertEquals(11.377778053283691, point2D_Double0.x, 0.01);
      assertNotNull(point2D_Double0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      float float0 = GeometricUtilities.getDeltaY((-3124.95066));
      assertEquals((-0.42408508F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      float float0 = GeometricUtilities.getDeltaY((double) 0);
      assertEquals(0.9999997F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      float float0 = GeometricUtilities.getDeltaX((-1850.987905031));
      assertEquals((-0.7773712F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float(5, 5, 5, 5);
      Area area0 = new Area(rectangle2D_Float0);
      List<Line2D.Double> list0 = GeometricUtilities.getConstrainingLines(area0);
      assertEquals(4, list0.size());
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      List<Point2D> list0 = GeometricUtilities.getPoints((Rectangle2D) rectangle2D_Float0);
      Point2D.Double point2D_Double0 = (Point2D.Double)GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      assertNotNull(point2D_Double0);
      
      Point2D.Double point2D_Double1 = (Point2D.Double)GeometricUtilities.project((Point2D) point2D_Double0, (Point2D) point2D_Double0, (double) 0.0F);
      double double0 = GeometricUtilities.calcRotationAngleInDegrees((Point2D) point2D_Double0, (Point2D) point2D_Double1);
      assertEquals(0.0, point2D_Double0.y, 0.01);
      assertEquals(0.0, point2D_Double0.x, 0.01);
      assertEquals(Double.NaN, point2D_Double1.y, 0.01);
      assertEquals(Double.NaN, double0, 0.01);
      assertEquals(Double.NaN, point2D_Double1.x, 0.01);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Point point0 = new Point();
      // Undeclared exception!
      try { 
        GeometricUtilities.project((Point2D) null, (Point2D) point0, (double) 0.0F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      Rectangle2D rectangle2D0 = GeometricUtilities.extrude(rectangle2D_Float0, 0.0F);
      assertEquals(0.0, rectangle2D0.getMaxY(), 0.01);
      assertEquals(0.0, rectangle2D0.getMaxX(), 0.01);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.distance((Point2D) null, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      // Undeclared exception!
      try { 
        GeometricUtilities.getPerpendicularIntersection(point2D_Double0, (Line2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Ellipse2D.Float ellipse2D_Float0 = new Ellipse2D.Float();
      // Undeclared exception!
      try { 
        GeometricUtilities.translateShape(ellipse2D_Float0, (Point2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      Point point0 = new Point((-42266383), (-42266383));
      Rectangle rectangle0 = new Rectangle(point0);
      Path2D.Double path2D_Double0 = (Path2D.Double)GeometricUtilities.scaleShape(rectangle0, 1600.0991667);
      assertEquals(1, path2D_Double0.getWindingRule());
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getCircle((Point2D) null, 1258.807948);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      List<Point2D> list0 = GeometricUtilities.getPoints((Rectangle2D) rectangle2D_Float0);
      Point2D.Double point2D_Double0 = (Point2D.Double)GeometricUtilities.getAveragePosition((Collection<Point2D>) list0);
      double double0 = GeometricUtilities.calcRotationAngleInDegrees((Point2D) point2D_Double0, (Point2D) point2D_Double0);
      assertEquals(0.0, point2D_Double0.x, 0.01);
      assertEquals(0.0, point2D_Double0.y, 0.01);
      assertEquals(90.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      // Undeclared exception!
      try { 
        GeometricUtilities.getPointOnCircle((Point2D) null, 1.0, 1.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.gurkenlabs.litiengine.util.geom.GeometricUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      Point2D.Float point2D_Float0 = new Point2D.Float();
      double double0 = GeometricUtilities.distance((Rectangle2D) rectangle2D_Float0, (Point2D) point2D_Float0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Point2D.Float point2D_Float0 = new Point2D.Float();
      Line2D.Double line2D_Double0 = new Line2D.Double(point2D_Float0, point2D_Float0);
      Point2D.Double point2D_Double0 = (Point2D.Double)GeometricUtilities.getCenter((Line2D) line2D_Double0);
      assertEquals(0.0, point2D_Double0.y, 0.01);
      assertEquals(0.0, point2D_Double0.x, 0.01);
  }
}
