/*
 * This file was automatically generated by EvoSuite
 * Mon May 24 12:25:01 GMT 2021
 */

package de.gurkenlabs.litiengine;

import org.junit.Test;
import static org.junit.Assert.*;
import de.gurkenlabs.litiengine.GameInfo;
import java.net.URL;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GameInfo_ESTest extends GameInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      
      gameInfo0.setWebsite("de.gurkenlabs.litiengine.environment.tilemap.xml.CustomProperty");
      gameInfo0.getWebsiteURL();
      assertEquals("v1.0", gameInfo0.getVersion());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      
      gameInfo0.setWebsite((String) null);
      gameInfo0.getWebsite();
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      
      gameInfo0.setWebsite("");
      gameInfo0.getWebsite();
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("v1.0", gameInfo0.getVersion());
      
      gameInfo0.setVersion((String) null);
      gameInfo0.getVersion();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("v1.0", gameInfo0.getVersion());
      
      gameInfo0.setVersion("");
      gameInfo0.getVersion();
      assertEquals("gurkenlabs", gameInfo0.getCompany());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      
      gameInfo0.setSubTitle((String) null);
      gameInfo0.getSubTitle();
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      
      gameInfo0.setSubTitle("");
      gameInfo0.getSubTitle();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      
      gameInfo0.setName("");
      gameInfo0.getName();
      assertEquals("gurkenlabs", gameInfo0.getCompany());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      gameInfo0.setDevelopers((String[]) null);
      gameInfo0.getDevelopers();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String[] stringArray0 = new String[0];
      gameInfo0.setDevelopers(stringArray0);
      gameInfo0.getDevelopers();
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      
      gameInfo0.setDescription((String) null);
      gameInfo0.getDescription();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      
      gameInfo0.setDescription("");
      gameInfo0.getDescription();
      assertEquals("LITIENGINE Game", gameInfo0.getName());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      
      String[] stringArray0 = new String[6];
      gameInfo0.setCompany(stringArray0[2]);
      gameInfo0.getCompany();
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      
      gameInfo0.setCompany("");
      gameInfo0.getCompany();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getWebsite();
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("https://litiengine.com", string0);
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("v1.0", gameInfo0.getVersion());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getSubTitle();
      assertEquals("The pure 2D java game engine", string0);
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getVersion();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("v1.0", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getName();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("LITIENGINE Game", string0);
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      
      gameInfo0.setSubTitle("");
      String string0 = gameInfo0.getTitle();
      assertEquals("LITIENGINE Game v1.0", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      
      gameInfo0.setSubTitle((String) null);
      String string0 = gameInfo0.getTitle();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("LITIENGINE Game v1.0", string0);
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      
      gameInfo0.setWebsite("");
      gameInfo0.getWebsiteURL();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      
      String[] stringArray0 = new String[6];
      gameInfo0.setWebsite(stringArray0[0]);
      gameInfo0.getWebsiteURL();
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      URL uRL0 = gameInfo0.getWebsiteURL();
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertNotNull(uRL0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String[] stringArray0 = gameInfo0.getDevelopers();
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals(2, stringArray0.length);
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      gameInfo0.getPublisher();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getDescription();
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("A game, created with the allmighty LITIENGINE.", string0);
      assertEquals("LITIENGINE Game", gameInfo0.getName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      
      gameInfo0.setName((String) null);
      gameInfo0.getName();
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("gurkenlabs", gameInfo0.getCompany());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getTitle();
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("LITIENGINE Game v1.0 - The pure 2D java game engine", string0);
      assertEquals("gurkenlabs", gameInfo0.getCompany());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      GameInfo gameInfo0 = new GameInfo();
      String string0 = gameInfo0.getCompany();
      assertEquals("A game, created with the allmighty LITIENGINE.", gameInfo0.getDescription());
      assertEquals("v1.0", gameInfo0.getVersion());
      assertEquals("The pure 2D java game engine", gameInfo0.getSubTitle());
      assertEquals("https://litiengine.com", gameInfo0.getWebsite());
      assertEquals("LITIENGINE Game", gameInfo0.getName());
      assertEquals("gurkenlabs", string0);
  }
}
